### ISSUE TITLE
A potential small bug 

### ISSUE THREAD

**Issue by chenfork** [Yu-Group/iterative-Random-Forest#11]
Hey, when I was doing some tests earlier today, I found this potential bug in get_tree_data().

https://github.com/Yu-Group/iterative-Random-Forest/blob/286d65b833c9167233d3d3bab625f6fd54d8c8b4/irf/utils.py#L143

`node_features_raw_idx` is just `tree_.feature`, that's clear, but for leaf nodes, the `feature` value is `TREE_UNDEFINED`, which is `-2`.
So, if you use `-2` in this `all_features_idx` array, you will get second to last feature id for your leaf node, not `-2` anymore.

Luckily, I see that you remove leaf node in the following code, I suppose this won't be a bug.
Still, I wonder is there a necessity to use `all_features_idx` rather than `node_features_raw_idx`? 
Thanks!

**Comment by shifwang** [comment]
I am not really sure about this, this part of the code is not used very often. Given the definition of all_features_idx, it does not seem to be necessary.

**Comment by chenfork** [comment]
That makes sense, thanks!
