### ISSUE TITLE
Tests post-installation failing

### ISSUE THREAD

**Issue by gkapatai** [Yu-Group/iterative-Random-Forest#4]
Hi, I followed the installation instructions in your README file and all was working perfect until i reached the tests. running the tests returns error:

File "/mnt/data01/analysis/gkapatai/software/external/iterative-Random-Forest/irf/ensemble/forest.py", line 64, in <module>
    from sklearn.utils.fixes import parallel_helper
ImportError: cannot import name 'parallel_helper'

The problem is not really in you code but in the fact that sklearn has now removed parallel_helper from sklearn.utils.fixes. See commit: https://github.com/scikit-learn/scikit-learn/commit/847b3468c7c60c7d89c21f5e854b6c492f7261d5

I was able to fix it by removing the import statement and the parallel_helper instances from line 177 and 208, similar to what was done in the commit page i shared above. Following these changes the tests run successfully.

**Comment by shifwang** [comment]
Thank you for letting us know! We will fix that in the main code.
